"""Migration 0001 against the test database: schema shape, round-trip, parity with the models."""

import asyncio

import pytest
from alembic import command
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncEngine

from tests.conftest import alembic_config, run_alembic

TABLES = {
    "phones",
    "phone_prices",
    "channels",
    "channel_videos",
    "review_videos",
    "transcripts",
    "phone_digests",
    "review_chunks",
    "job_runs",
    "query_logs",
}
INDEXES = {
    "ix_phones_is_active_price_from",
    "ix_channel_videos_channel_id",
    "ix_channel_videos_title_tsv",
    "ix_review_videos_status",
    "ix_review_videos_video_id",
    "ix_review_chunks_embedding",
    "ix_job_runs_job_started_at",
    "ix_query_logs_session_id",
}


async def _tables(engine: AsyncEngine) -> set[str]:
    async with engine.connect() as conn:
        rows = await conn.execute(
            text("SELECT tablename FROM pg_tables WHERE schemaname = 'public'")
        )
        return {r[0] for r in rows} - {"alembic_version"}


async def _indexdefs(engine: AsyncEngine) -> dict[str, str]:
    async with engine.connect() as conn:
        rows = await conn.execute(
            text("SELECT indexname, indexdef FROM pg_indexes WHERE schemaname = 'public'")
        )
        return {r[0]: r[1] for r in rows}


async def test_test_database_is_separate(migrated_db: AsyncEngine) -> None:
    async with migrated_db.connect() as conn:
        name = await conn.scalar(text("SELECT current_database()"))
    assert name == "phonematch_test"


async def test_upgrade_creates_schema(migrated_db: AsyncEngine) -> None:
    assert await _tables(migrated_db) == TABLES

    indexdefs = await _indexdefs(migrated_db)
    assert indexdefs.keys() >= INDEXES
    assert "USING hnsw (embedding vector_cosine_ops)" in indexdefs["ix_review_chunks_embedding"]
    assert (
        "USING gin (to_tsvector('simple'::regconfig, title))"
        in (indexdefs["ix_channel_videos_title_tsv"])
    )
    assert "(job, started_at DESC)" in indexdefs["ix_job_runs_job_started_at"]

    async with migrated_db.connect() as conn:
        ext = await conn.scalar(text("SELECT extversion FROM pg_extension WHERE extname='vector'"))
        dim_type = await conn.scalar(
            text(
                "SELECT format_type(atttypid, atttypmod) FROM pg_attribute "
                "WHERE attrelid = 'review_chunks'::regclass AND attname = 'embedding'"
            )
        )
    assert ext is not None
    assert tuple(int(p) for p in ext.split(".")[:2]) >= (0, 8)
    assert dim_type == "vector(384)"


async def test_models_match_migration(migrated_db: AsyncEngine) -> None:
    try:
        await asyncio.to_thread(command.check, alembic_config())
    except AutogenerateDiffsDetected as exc:
        pytest.fail(f"Models and migrations differ:\n{exc}")


async def test_downgrade_then_upgrade(migrated_db: AsyncEngine) -> None:
    await run_alembic("downgrade", "base")
    try:
        assert await _tables(migrated_db) == set()
        assert not INDEXES & (await _indexdefs(migrated_db)).keys()
    finally:
        await run_alembic("upgrade", "head")
    assert await _tables(migrated_db) == TABLES
